set(stm32f0xx_CPU_PAR                 "-mcpu=cortex-m0" "-mfloat-abi=soft")
set(stm32f1xx_CPU_PAR                 "-mcpu=cortex-m3" "-mfloat-abi=soft")
set(stm32f2xx_CPU_PAR                 "-mcpu=cortex-m3" "-mfloat-abi=soft")
set(stm32f3xx_CPU_PAR                 "-mcpu=cortex-m4" "-mfpu=fpv4-sp-d16" "-mfloat-abi=hard")
set(stm32f4xx_CPU_PAR                 "-mcpu=cortex-m4" "-mfpu=fpv4-sp-d16" "-mfloat-abi=hard")
set(stm32f7xx_CPU_PAR                 "-mcpu=cortex-m7" "-mfpu=fpv5-sp-d16" "-mfloat-abi=hard")
set(stm32h7xx_CPU_PAR                 "-mcpu=cortex-m7" "-mfpu=fpv5-d16" "-mfloat-abi=hard")
set(stm32g0xx_CPU_PAR                 "-mcpu=cortex-m0plus" "-mfloat-abi=soft")
set(stm32g4xx_CPU_PAR                 "-mcpu=cortex-m4" "-mfpu=fpv4-sp-d16" "-mfloat-abi=hard")
set(stm32l0xx_CPU_PAR                 "-mcpu=cortex-m0plus" "-mfloat-abi=soft")
set(stm32l1xx_CPU_PAR                 "-mcpu=cortex-m3" "-mfloat-abi=soft")
set(stm32l4xx_CPU_PAR                 "-mcpu=cortex-m4" "-mfpu=fpv4-sp-d16" "-mfloat-abi=hard")
set(stm32l5xx_CPU_PAR                 "-mcpu=cortex-m33" "-mfpu=fpv5-sp-d16" "-mfloat-abi=hard")
set(stm32u5xx_CPU_PAR                 "-mcpu=cortex-m33" "-mfpu=fpv5-sp-d16" "-mfloat-abi=hard")
set(stm32wbxx_CPU_PAR                 "-mcpu=cortex-m4" "-mfpu=fpv4-sp-d16" "-mfloat-abi=hard")
set(stm32wlxx_cm4_CPU_PAR             "-mcpu=cortex-m4" "-mfloat-abi=soft")
set(stm32wlxx_cm0_CPU_PAR             "-mcpu=cortex-m0plus" "-mfloat-abi=soft")
